clear;clc;close all;
a=1; b=1; c=1;
u=linspace(-2,2,40);
v=linspace(0,2*pi,40);
[u,v]=meshgrid(u,v);
x=a*cosh(u).*cos(v);
y=b*cosh(u).*sin(v);
z=c*sinh(u);
surfc(x,y,z);
labels;
title('Tek Parçali Hiperboloid');
figure;
subplot(132);
plot(x,z);
title('Tek Parçali Hiperboloid''in yan görünümü (XZ)');
labels;
subplot(131);
plot(x,y);
title('Tek Parçali Hiperboloid''in üst görünümü (XY)');
labels;
subplot(133);
plot(z,y);
title('Tek Parçali Hiperboloid''in yan görünümü (ZY)');
labels;