clear;clc;close all;
[x,y,z] = sphere; %Kure olusturma Built-in Fonk.
hold on; 
x=2.*x;
y=2.*y;
z=2.*z;
meshc(x,y,z);labels;
figure;
subplot(131);
plot(x,y);
hold on;
subplot(132);
plot(x,z);
hold on;
subplot(133);
plot(y,z);
hold on;
figure(1);
x=3.*x;
y=3.*y;
z=3.*z;
surfc(x,y,z);
figure(2);
subplot(131);
plot(x,y);labels;
title('Kürenin üst görünümü (XY)');
subplot(132);
plot(x,z);labels;
title('Kürenin yan görünümü (XZ)');
subplot(133);
title('Kürenin yan görünümü (YZ)');
plot(y,z);labels;
hold off;
